'use strict'
export let formObj={
    selectF:{
        tagName:"select",
        id:"sel"
    },
    opt1:{
        parentTag:"select",
        tagName:"option",
        value:"1",
        textTag:"NN"
    },
    opt2:{
        parentTag:"select",
        tagName:"option",
        value:"2",
        textTag:"Moscow"
    },
    login:{
        tagName:"input",
        type:"text",
        id:"log",
        placeholder:"login",
        reg:"[a-zA-Z]{6,}",
        required:"",
        class:"input"
    },
    pwd:{
        tagName:"input",
        type:"text",
        id:"pwd",
        placeholder:"password",
        reg:"\w{6,}",
        required:"",
        class:"input"
    },
    politika:{
        tagName:"input",
        type:"checkbox",
        id:"politika",
        placeholder:"password",
        class:"checkbox",
        textTag:"checkbox"
    },
    prim:{
        tagName:"textarea",
        id:"prim",
        row:"100",
        col:"200"
    },
    radioN:{
        tagName:"input",
        id:"r2",
        type:"radio",
        name:"r1",
        textTag:"radio1"
    },
    radioN1:{
        tagName:"input",
        id:"r1",
        type:"radio",
        name:"r1",
        textTag:"radio2"
    },
    
   
}